<?php

namespace Tests\Unit;

use App\Services\TokenAuthService;
use PHPUnit\Framework\TestCase;

class ExampleTest extends TestCase
{
    public static function setUpBeforeClass(): void
    {
        parent::setUpBeforeClass(); // TODO: Change the autogenerated stub
    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * A basic test example.
     *
     * @return void
     */
    public function testBasicTest()
    {
        /** @var TokenAuthService $service */
        $service = app(TokenAuthService::class);
        $this->assertTrue($service->checkAuthToken());
    }

}
